#!/bin/bash

TOPIC=$1
HOST=$2
LOGDIR=$3

if [ ! -d $LOGDIR/$TOPIC ] 
then
  echo creating $LOGDIR/$TOPIC
  mkdir -p $LOGDIR/$TOPIC
fi

LOG=$LOGDIR/$TOPIC/`date +%s`

(mosquitto_sub -h $HOST -v -t $TOPIC -t $TOPIC/# | ( while read t v ; do echo `date +%s`,`date -R`,$t,$v >> $LOG; done )) &


